# Generated by Django 3.2.6 on 2021-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211013_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user_id',
        ),
        migrations.AddField(
            model_name='employees',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
